apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
  namespace: ride-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
      - name: driver-service
        image: pratikgajbar/driver-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        envFrom:
        - secretRef:
            name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: ride-platform
spec:
  selector:
    app: driver-service
  ports:
  - port: 8083
    targetPort: 8083
