apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  namespace: ride-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
      - name: location-service
        image: pratikgajbar/location-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
        envFrom:
        - secretRef:
            name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: ride-platform
spec:
  selector:
    app: location-service
  ports:
  - port: 8086
    targetPort: 8086
