apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ride-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: pratikgajbar/payment-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        envFrom:
        - secretRef:
            name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ride-platform
spec:
  selector:
    app: payment-service
  ports:
  - port: 8085
    targetPort: 8085
