apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ride-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: pratikgajbar/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        envFrom:
        - secretRef:
            name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ride-platform
spec:
  selector:
    app: user-service
  ports:
  - port: 8082
    targetPort: 8082
